use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct HubertConfig {
    pub activation_dropout: f64,
    pub apply_spec_augment: bool,
    pub attention_dropout: f64,
    pub bos_token_id: usize,
    pub classifier_proj_size: usize,
    pub conv_bias: bool,
    pub conv_dim: Vec<usize>,
    pub conv_kernel: Vec<usize>,
    pub conv_pos_batch_norm: bool,
    pub conv_stride: Vec<usize>,
    pub ctc_loss_reduction: String,
    pub ctc_zero_infinity: bool,
    pub do_stable_layer_norm: bool,
    pub eos_token_id: usize,
    pub feat_extract_activation: String,
    pub feat_extract_norm: String,
    pub feat_proj_dropout: f64,
    pub feat_proj_layer_norm: bool,
    pub final_dropout: f64,
    pub hidden_act: String,
    pub hidden_dropout: f64,
    pub hidden_size: usize,
    pub initializer_range: f64,
    pub intermediate_size: usize,
    pub layer_norm_eps: f64,
    pub layerdrop: f64,
    pub mask_feature_length: usize,
    pub mask_feature_min_masks: usize,
    pub mask_feature_prob: f64,
    pub mask_time_length: usize,
    pub mask_time_min_masks: usize,
    pub mask_time_prob: f64,
    pub model_type: String,
    pub num_attention_heads: usize,
    pub num_conv_pos_embedding_groups: usize,
    pub num_conv_pos_embeddings: usize,
    pub num_feat_extract_layers: usize,
    pub num_hidden_layers: usize,
    pub pad_token_id: usize,
    pub use_weighted_layer_sum: bool,
    pub vocab_size: usize,
}
