use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Serialize, Deserialize)]
pub struct HubertConfig {
    pub activation_dropout: f64,
    pub apply_spec_augment: bool,
    pub attention_dropout: f64,
    pub bos_token_id: usize,
    pub classifier_proj_size: usize,
    pub conv_bias: bool,
    pub conv_dim: Vec<usize>,
    pub conv_kernel: Vec<usize>,
    pub conv_pos_batch_norm: bool,
    pub conv_stride: Vec<usize>,
    pub ctc_loss_reduction: String,
    pub ctc_zero_infinity: bool,
    pub do_stable_layer_norm: bool,
    pub eos_token_id: usize,
    pub feat_extract_activation: String,
    pub feat_extract_norm: String,
    pub feat_proj_dropout: f64,
    pub feat_proj_layer_norm: bool,
    pub final_dropout: f64,
    pub hidden_act: String,
    pub hidden_dropout: f64,
    pub hidden_size: usize,
    pub initializer_range: f64,
    pub intermediate_size: usize,
    pub layer_norm_eps: f64,
    pub layerdrop: f64,
    pub mask_feature_length: usize,
    pub mask_feature_min_masks: usize,
    pub mask_feature_prob: f64,
    pub mask_time_length: usize,
    pub mask_time_min_masks: usize,
    pub mask_time_prob: f64,
    pub model_type: String,
    pub num_attention_heads: usize,
    pub num_conv_pos_embedding_groups: usize,
    pub num_conv_pos_embeddings: usize,
    pub num_feat_extract_layers: usize,
    pub num_hidden_layers: usize,
    pub pad_token_id: usize,
    pub use_weighted_layer_sum: bool,
    pub vocab_size: usize,
}

pub fn get_config() -> HubertConfig {
    serde_json::from_value::<HubertConfig>(json!(
    {
        "activation_dropout": 0.1,
        "apply_spec_augment": true,
        "attention_dropout": 0.1,
        "bos_token_id": 1,
        "classifier_proj_size": 256,
        "conv_bias": false,
        "conv_dim": [
          512,
          512,
          512,
          512,
          512,
          512,
          512
        ],
        "conv_kernel": [
          10,
          3,
          3,
          3,
          3,
          2,
          2
        ],
        "conv_pos_batch_norm": false,
        "conv_stride": [
          5,
          2,
          2,
          2,
          2,
          2,
          2
        ],
        "ctc_loss_reduction": "sum",
        "ctc_zero_infinity": false,
        "do_stable_layer_norm": false,
        "eos_token_id": 2,
        "feat_extract_activation": "gelu",
        "feat_extract_norm": "group",
        "feat_proj_dropout": 0.0,
        "feat_proj_layer_norm": true,
        "final_dropout": 0.1,
        "hidden_act": "gelu",
        "hidden_dropout": 0.1,
        "hidden_size": 768,
        "initializer_range": 0.02,
        "intermediate_size": 3072,
        "layer_norm_eps": 1e-05,
        "layerdrop": 0.1,
        "mask_feature_length": 10,
        "mask_feature_min_masks": 0,
        "mask_feature_prob": 0.0,
        "mask_time_length": 10,
        "mask_time_min_masks": 2,
        "mask_time_prob": 0.0,
        "model_type": "hubert",
        "num_attention_heads": 12,
        "num_conv_pos_embedding_groups": 16,
        "num_conv_pos_embeddings": 128,
        "num_feat_extract_layers": 7,
        "num_hidden_layers": 12,
        "pad_token_id": 0,
        "use_weighted_layer_sum": false,
        "vocab_size": 32
      }
        ))
    .unwrap()
}
